# Generated by Django 4.0.3 on 2022-04-25 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("obapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sequence",
            name="slug",
            field=models.SlugField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="download_timestamp",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="download date"
            ),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="owner",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="sequence",
            constraint=models.UniqueConstraint(
                fields=("owner", "slug"), name="unique_sequence_slug"
            ),
        ),
    ]
