# Generated by Django 4.0.3 on 2022-04-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obapi", "0002_sequence_slug_alter_contentitem_download_timestamp_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="authoralias",
            name="authoralias_is_unique",
        ),
        migrations.RemoveConstraint(
            model_name="ideaalias",
            name="ideaalias_is_unique",
        ),
        migrations.RemoveConstraint(
            model_name="tagalias",
            name="tagalias_is_unique",
        ),
        migrations.RemoveConstraint(
            model_name="topicalias",
            name="topicalias_is_unique",
        ),
        migrations.RemoveField(
            model_name="author",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="idea",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="slug",
        ),
        migrations.AlterField(
            model_name="authoralias",
            name="text",
            field=models.SlugField(
                help_text="Alias text.", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="ideaalias",
            name="text",
            field=models.SlugField(
                help_text="Alias text.", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="tagalias",
            name="text",
            field=models.SlugField(
                help_text="Alias text.", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="topicalias",
            name="text",
            field=models.SlugField(
                help_text="Alias text.", max_length=100, unique=True
            ),
        ),
    ]
