# Generated by Django 4.0.3 on 2022-04-26 12:18

import obapi.modelfields
from django.db import migrations
from obapi import utils


def save_aliased_models(apps, schema_editor):
    for model_name in ["author", "idea", "tag", "topic"]:
        model = apps.get_model("obapi", model_name)
        db_alias = schema_editor.connection.alias
        for obj in model.objects.using(db_alias).all():
            obj.slug = utils.slugify(obj.name)
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("obapi", "0004_alter_authoralias_text_alter_ideaalias_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="slug",
            field=obapi.modelfields.SimpleSlugField(
                default="default", editable=False, max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="idea",
            name="slug",
            field=obapi.modelfields.SimpleSlugField(
                default="default", editable=False, max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=obapi.modelfields.SimpleSlugField(
                default="default", editable=False, max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topic",
            name="slug",
            field=obapi.modelfields.SimpleSlugField(
                default="default", editable=False, max_length=100
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=save_aliased_models, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="author",
            name="slug",
            field=obapi.modelfields.SimpleSlugField(
                editable=False, max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="idea",
            name="slug",
            field=obapi.modelfields.SimpleSlugField(
                editable=False, max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=obapi.modelfields.SimpleSlugField(
                editable=False, max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=obapi.modelfields.SimpleSlugField(
                editable=False, max_length=100, unique=True
            ),
        ),
    ]
