# Generated by Django 4.0.3 on 2022-04-26 12:18

import obapi.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obapi", "0004_alter_authoralias_text_alter_ideaalias_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="slug",
            field=obapi.modelfields.SimpleSlugField(
                default="default", editable=False, max_length=100, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="idea",
            name="slug",
            field=obapi.modelfields.SimpleSlugField(
                default="default", editable=False, max_length=100, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=obapi.modelfields.SimpleSlugField(
                default="default", editable=False, max_length=100, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topic",
            name="slug",
            field=obapi.modelfields.SimpleSlugField(
                default="default", editable=False, max_length=100, unique=True
            ),
            preserve_default=False,
        ),
    ]
