# Generated by Django 4.0.3 on 2022-04-26 12:30

import obapi.modelfields
from django.db import migrations
from obapi import utils


def save_sequences(apps, schema_editor):
    Sequence = apps.get_model("obapi", "sequence")
    db_alias = schema_editor.connection.alias
    for obj in Sequence.objects.using(db_alias).all():
        obj.slug = utils.slugify(obj.name)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("obapi", "0005_author_slug_idea_slug_tag_slug_topic_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequence",
            name="slug",
            field=obapi.modelfields.SimpleSlugField(
                default="default", editable=False, max_length=100
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=save_sequences, reverse_code=migrations.RunPython.noop
        ),
    ]
