# Generated by Django 4.0.3 on 2022-04-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obapi", "0006_alter_sequence_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sequence",
            old_name="description",
            new_name="abstract",
        ),
    ]
